{"imagem": "https://static.metacritic.com/images/products/movies/3/47c2b1f35087fc23c5ce261bbc3ad9e0-98.jpg", "nome": "The Godfather", "descricao": "\n                        Francis Ford Coppola's epic features Marlon Brando in his Oscar-winning role as the patriarch of the Corleone family. Director Coppola paints a chilling portrait of the Sicilian clan's rise and near fall from power in America, masterfully balancing the story between the Corleone's family life and the ugly crime business in which they are engaged. Based on Mario Puzo's best-selling novel and featuring career-making performances by Al Pacino, James Caan and Robert Duvall, this searing and brilliant film garnered ten Academy Award nominations, and won three including Best Picture of 1972. [Paramount Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/1c4da52a6f2335836a21271ec4a6f6b3-98.jpg", "nome": "Citizen Kane", "descricao": "\n                        Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/0d63e9ade174d351943b09982a5022fe-98.jpg", "nome": "Rear Window", "descricao": "\n                        A wheelchair-bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/2e9475e10998b61bf8a18fd38436a30e-98.jpg", "nome": "Casablanca", "descricao": "\n                        A Casablanca, Morocco casino owner in 1941 shelters his former lover and her husband, a Czechoslovakian freedom fighter, from the Nazis.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/e418f13ee37a8e9c864e60c512699d65-98.jpg", "nome": "Boyhood", "descricao": "\n                        Filmed over 12 years with the same cast, Richard Linklater's Boyhood is a groundbreaking story of growing up as seen through the eyes of a child named Mason (Ellar Coltrane), who literally grows up on screen before our eyes. Starring Ethan Hawke and Patricia Arquette as Mason's parents and newcomer Lorelei Linklater as his sister Samantha, Boyhood charts the rocky terrain of childhood like no other film has before and is both a nostalgic time capsule of the recent past and an ode to growing up and parenting. [IFC Films]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/cb3524a14b6375d42934270defe3aaca-98.jpg", "nome": "Three Colors: Red", "descricao": "\n                        Krzysztof Kieslowski closes his Three Colors trilogy in grand fashion, with an incandescent meditation on fate and chance, starring Ir\u00e8ne Jacob as a sweet-souled yet somber runway model in Geneva whose life dramatically intersects with that of a bitter retired judge, played by Jean-Louis Trintignant. Meanwhile, just down the street, a seemingly unrelated story of jealousy and betrayal unfolds. Red is an intimate look at forged connections and a splendid final statement from a remarkable filmmaker at the height of his powers. [Criterion]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/c6848f47fbf9db70bfbcba21d48c969f-98.jpg", "nome": "Vertigo", "descricao": "\n                        Vertigo creates a dizzying web of mistaken identity, passion and murder after an acrophobic detective rescues a mysterious blonde from the bay. [Universal Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/8cadf0ae5f802a9dd798367af49e1637-98.jpg", "nome": "Notorious", "descricao": "\n                        A woman is asked to spy on a group of Nazi friends in South America. How far will she have to go to ingratiate herself with them?\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/a82c621c24693dd1a9787b508cdf311d-98.jpg", "nome": "Singin' in the Rain", "descricao": "\n                        A silent film production company and cast make a difficult transition to sound.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/c715885f7f4cce709d2d5136a3801beb-98.jpg", "nome": "City Lights", "descricao": "\n                        The Tramp (Charlie Chaplin) struggles to help a blind flower girl he has fallen in love with.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/4dd5f999a98b592d830105797a96f03f-98.jpg", "nome": "Moonlight", "descricao": "\n                        Moonlight is the tender, heartbreaking story of a young man\u2019s struggle to find himself, told across three defining chapters in his life as he experiences the ecstasy, pain, and beauty of falling in love, while grappling with his own sexuality.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/27fdc2a71b8c8f933dc7fd750e0a9cf2-98.jpg", "nome": "Intolerance", "descricao": "\n                        The story of a poor young woman, separated by prejudice from her husband and baby, is interwoven with tales of intolerance from throughout history.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/cc1ed146d2f7096679a6eca9c9e49b70-98.jpg", "nome": "Pinocchio", "descricao": "\n                        A living puppet, with the help of a cricket as his conscience, must prove himself worthy to become a real boy.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/3c0a1271548af503f635d787eb0eedf3-98.jpg", "nome": "Touch of Evil", "descricao": "\n                        This film noir portrait of corruption and morally-compromised obsessions stars Welles as Hank Quinlan, a crooked police chief who frames a Mexican youth as part of an intricate criminal plot. Charlton Heston plays an honorable Mexican narcotics investigator who clashes with the bigoted Quinlan after probing into his dark past. A memorable supporting cast including Janet Leigh as Heston's inquisitive wife, Akim Tamiroff as a seedy underworld leader, Zsa Zsa Gabor and Marlene Dietrich as an enigmatic gypsy complete this fascinating drama engulfed in haunting cinematography and a magnificently eerie score by Henry Mancini.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/8a22da4899fba5c8fe3ed7b09cafc517-98.jpg", "nome": "The Lady Vanishes", "descricao": "\n                        While travelling in continental Europe, a rich young playgirl realizes that an elderly lady seems to have disappeared from the train.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/aa1e15b06bed9503511eb13f85ad333d-98.jpg", "nome": "The Treasure of the Sierra Madre", "descricao": "\n                        Fred Dobbs and Bob Curtin, two Americans searching for work in Mexico, convince an old prospector to help them mine for gold in the Sierra Madre Mountains.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/8eb6412f31967db627287790e47ce0ff-98.jpg", "nome": "Pan's Labyrinth", "descricao": "\n                        Following a bloody civil war, young Ofelia enters a world of unimaginable cruelty when she moves in with her new stepfather, a tyrannical military officer. Armed with only her imagination, Ofelia discovers a mysterious labyrinth and meets a faun who sets her on a path to saving herself and her ailing mother. But soon, the lines between fantasy and reality begin to blur, and before Ofelia can turn back, she finds herself at the center of a ferocious battle between good and evil. [Warner Bros.]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/693e7413635830d3e9dce8b7569ce04a-98.jpg", "nome": "Some Like It Hot", "descricao": "\n                        When two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/ee29e1899f89829dc0067bd66ea4436e-98.jpg", "nome": "North by Northwest", "descricao": "\n                        A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/18e6a88baf392f8b0f84213eed85be13-98.jpg", "nome": "Hoop Dreams", "descricao": "\n                        Two inner-city Chicago boys with hopes of becoming professional basketball players struggle to become college players.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/a72283857efd64ec73d13e110e0de625-98.jpg", "nome": "Rashomon", "descricao": "\n                        The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai's ghost and a woodcutter.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/6480fd4c7a013454c0af2e5351f7fa97-98.jpg", "nome": "All About Eve", "descricao": "\n                        An ingenue insinuates herself into the company of an established but aging stage actress and her circle of theater friends.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/3c5bf40cae820d479f5742e606d45b94-98.jpg", "nome": "Jules and Jim", "descricao": "\n                        Decades of a love triangle concerning two friends and an impulsive woman.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/789494201584d839460c78bc1050c862-98.jpg", "nome": "The Wild Bunch", "descricao": "\n                        An aging group of outlaws look for one last big score as the \"traditional\" American West is disappearing around them.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/e48ade8e818926f8f6597972f29a0ae5-98.jpg", "nome": "My Left Foot", "descricao": "\n                        True story of cerebral palsied Christy Brown, who overcame his illness and poverty to become an accomplished artist, poet and writer. \n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/d3b79117720d899ad23c4b1dd5d775bd-98.jpg", "nome": "The Third Man", "descricao": "\n                        Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/a5b136464d1e19692af07939f2fb318e-98.jpg", "nome": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", "descricao": "\n                        Through a series of military and political accidents, a psychotic general - U.S. Air Force Commander Jack D. Ripper (Hayden) - triggers an ingenious, irrevocable scheme to attack Russia's strategic targets with nuclear bombs. The U.S. President (Sellers) and Dr. Strangelove (Sellers), a wheelchair-bound nuclear scientist who has bizarre ideas about man's future, work with the Soviet premier in a desperate effort to save the world.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/ce052d31ece8e28d24d4d09e62745b2a-98.jpg", "nome": "Quo Vadis, Aida?", "descricao": "\n                        Bosnia, July 11th 1995.  Aida is a translator for the United Nations in the small town of Srebrenica. When the Serbian army takes over the town, her family is among the thousands of citizens looking for shelter in the UN camp. As an insider to the negotiations Aida has access to crucial information that she needs to interpret. What is at the horizon for her family and people - rescue or death? Which move should she take? [Super LTD]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/dbe5b75dc0715eda6c92efd1c5060406-98.jpg", "nome": "Gone with the Wind", "descricao": "\n                        A Southern belle struggles with the devastation of the Civil War and Reconstruction. This classic won 8 Academy Awards, including Best Picture.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/b8472c8742b0065668c2a9dcb5b7e66a-98.jpg", "nome": "4 Months, 3 Weeks and 2 Days", "descricao": "\n                        During the final days of communism in Romania, two college roommates Otilia and Gabita are busy preparing for a night away. But rather than planning for a holiday, they are making arrangements for Gabita's illegal abortion and unwittingly, both find themselves burrowing deep down a rabbit hole of unexpected revelations. [IFC Films]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/5d4f62de038a8b8cbabf13936dddda53-98.jpg", "nome": "Psycho", "descricao": "\n                        A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man, Norman Bates (Anthony Perkins) under the domination of his mother.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/7e9bfecfd92a84830fc3784b769c7515-98.jpg", "nome": "Battleship Potemkin", "descricao": "\n                        In the midst of the Russian Revolution of 1905, the crew of the battleship Potemkin mutiny against the brutal, tyrannical regime of the vessel's officers. The resulting street demonstration in Odessa brings on a police massacre.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/f32747f2278d7608a5c8250ee304397b-98.jpg", "nome": "A Streetcar Named Desire", "descricao": "\n                        Disturbed Blanche DuBois (Vivien Leigh) moves in with her sister in New Orleans and is tormented by her brutish brother-in-law (Marlon Brando) while her reality crumbles around her.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/6c6e30725cb5b244cabe81943d0a1d6f-98.jpg", "nome": "The Maltese Falcon", "descricao": "\n                        A private detective (Humphrey Bogart) takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/a1639ff7f7ba20a70543f8b3b87c8182-98.jpg", "nome": "American Graffiti", "descricao": "\n                        A couple of high school grads spend one final night cruising the strip with their buddies before they go off to college.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/3d47987bfdeb326a5349e15bee83e750-98.jpg", "nome": "Dumbo", "descricao": "\n                        This simple animated tale is set in a circus and spotlights a baby elephant, Dumbo, who is mocked and ridiculed because his ears are too big, only to be assisted by a mouse to achieve his full potential.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/9b93199016c71cae5adb7e6355fb351a-98.jpg", "nome": "Roma", "descricao": "\n                        Roma follows Cleo (Yalitza Aparicio), a young domestic worker for a family in the middle-class neighborhood of Roma in Mexico City. Delivering an artful love letter to the women who raised him, Cuar\u00f3n draws on his own childhood to create a vivid and emotional portrait of domestic strife and social hierarchy amidst political turmoil of the 1970s. [Netflix]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/1b463a817a4d11e880d814759a20ca8e-98.jpg", "nome": "Ran", "descricao": "\n                        An adaptation of William Shakespeare\u2019s King Lear, Ran considers the disastrous consequences of Lord Hidetora Ichimonji\u2019s (Tatsuya Nakadai) decision to split his kingdom among his three sons.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/d7540b506275ecdeffbc2b8a9a09a82a-98.jpg", "nome": "Summer of Soul (...Or, When the Revolution Could Not Be Televised)", "descricao": "\n                        In 1969, during the same summer as Woodstock, a different music festival took place 100 miles away. More than 300,000 people attended the summer concert series known as the Harlem Cultural Festival. It was filmed, but after that summer, the footage sat in a basement for 50 years. It has never been seen. Until now. [Sundance]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/a916bf26d153617294f30d0cf68e583c-98.jpg", "nome": "The Shop Around the Corner", "descricao": "\n                        Two employees at a gift shop can barely stand each other, without realizing that they are falling in love through the post as each other's anonymous pen pal.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/10cfbf545224a82d585785f8b479cbe1-98.jpg", "nome": "12 Angry Men", "descricao": "\n                        12 Angry Men, by Sidney Lumet, is a behind-closed-doors look at the American legal system. This iconic adaptation of Reginald Rose\u2019s teleplay stars Henry Fonda as the dissenting member on a jury of white men ready to pass judgment on a Puerto Rican teenager charged with murdering his father. The result is a saga of epic proportions that plays out over a tense afternoon in one sweltering room.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/befe0fb1c3b6927407a0e5f2199295a0-98.jpg", "nome": "Rosemary's Baby", "descricao": "\n                        A young couple move into an apartment, only to be surrounded by peculiar neighbors and occurrences. When the wife becomes mysteriously pregnant, paranoia over the safety of her unborn child begins to control her life.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/3910c2e8cfefeb21fcd6079451336f86-98.jpg", "nome": "12 Years a Slave", "descricao": "\n                        In the pre-Civil War United States, Solomon Northup, a free black man living in upstate New York, is abducted and sold into slavery.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/3faf6055d74f395e0089a36c2d2ee0f9-98.jpg", "nome": "Manchester by the Sea", "descricao": "\n                        After the death of his older brother Joe (Kyle Chandler), Lee Chandler (Casey Affleck) is shocked to learn that Joe has made him sole guardian of his nephew Patrick (Lucas Hedges). Taking leave of his job, Lee reluctantly returns to Manchester-by-the-Sea to care for Patrick, a spirited 15-year-old, and is forced to deal with a past that separated him from his wife Randi (Michelle Williams) and the community where he was born and raised.   Bonded by the man who held their family together, Lee and Patrick struggle to adjust to a world without him.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/1eab36fe54ed63aff9b43e8b0b8bf15c-98.jpg", "nome": "Killer of Sheep", "descricao": "\n                        Killer of Sheep examines the black Los Angeles ghetto of Watts in the mid-1970s through the eyes of Stan, a sensitive dreamer who is growing detached and numb from the psychic toll of working at a slaughterhouse. The film offers no solutions; it merely presents life -- sometimes hauntingly bleak, sometimes filled with transcendent joy and gentle humor.  [Milestone Film & Video]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/bfc0d6ce01bbacfcf214a781a4fc7b6f-98.jpg", "nome": "Nashville", "descricao": "\n                        Over the course of a few hectic days, numerous interrelated people prepare for a political convention as secrets and lies are surfaced and revealed.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/da285e5670a27e634796c2ca8402f5ed-98.jpg", "nome": "Ratatouille", "descricao": "\n                        Despite his sensational sniffer and sophisticated palate, Remy's dreams of becoming a chef seem hopeless due to one small detail--he's a rat! Through a twist of fate, he ends up in the world-famous restaurant of his late hero, Auguste Gusteau. With a dash of culinary courage and the help of garbage boy Linguini, Remy whips up exquisite meals that impress even the nasty chef Skinner and food critic Anton Ego. Together they conquer the kitchen and prove that big dreams can come true no matter how small you are. [Disney]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/b0eb57fd63df90ca7e654c788f5851a8-98.jpg", "nome": "Parasite", "descricao": "\n                        Meet the Park Family: the picture of aspirational wealth. And the Kim Family, rich in street smarts but not much else. Be it chance or fate, these two houses are brought together and the Kims sense a golden opportunity. Masterminded by college-aged Ki-woo, the Kim children expediently install themselves as tutor and art therapist, to the Parks. Soon, a symbiotic relationship forms between the two families. The Kims provide \u201cindispensable\u201d luxury services while the Parks obliviously bankroll their entire household. When a parasitic interloper threatens the Kims\u2019 newfound comfort, a savage, underhanded battle for dominance breaks out, threatening to destroy the fragile ecosystem between the Kims and the Parks. [Neon]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/0fe69ceffacc925f74bc5a1382ce55aa-98.jpg", "nome": "The Grapes of Wrath", "descricao": "\n                        A poor Midwest family is forced off their land. They travel to California, suffering the misfortunes of the homeless in the Great Depression.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/d72c821d47c7499ab44db6e97f98d0fe-98.jpg", "nome": "Children of Paradise (1945)", "descricao": "\n                        Children of Paradise is the tale of a woman loved by four different men. Deftly entwining theater, literature, music, and design, director Marcel Carn\u00e9 and screenwriter Jacques Pr\u00e9vert resurrect the tumultuous world of nineteenth-century Paris, teeming with hucksters and aristocrats, thieves and courtesans, pimps and seers. (Janus Films)\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/549f6ebebdf6c345cfb16cc9bc2448a0-98.jpg", "nome": "Mean Streets", "descricao": "\n                        Charlie (Harvey Keitel) is working his way up the ranks of a local mob. Teresa (Amy Robinson) is the girlfriend his family deems unsuitable because of her epilepsy. Johnny Boy (Robert De Niro) is a small-time gambler in big-time debt to loan sharks. This is a story Martin Scorsese lived, a semi-biographical tale of the first-generation sons and daughters of New York's Little Italy. [Warner Bros.]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/9be4fbb5513231e284480d4e7b027a00-98.jpg", "nome": "Sansho the Bailiff", "descricao": "\n                        When an idealistic governor disobeys the reigning feudal lord, he is cast into exile, his wife and children left to fend for themselves and eventually wrenched apart by vicious slave traders. Under Kenji Mizoguchi\u2019s dazzling direction, this classic Japanese story became one of cinema\u2019s greatest masterpieces, a monumental, empathetic expression of human resilience in the face of evil.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/d4d0d28a23d9695330c3ebcc2fb674a2-98.jpg", "nome": "The Lady Eve", "descricao": "\n                        A trio of classy card sharks targets the socially awkward heir to brewery millions for his money, until one of them falls in love with him.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/1c2a9fd05698fdfa8f1d7ace302c7b6e-98.jpg", "nome": "Gravity", "descricao": "\n                        Dr. Ryan Stone (Sandra Bullock) is a brilliant medical engineer on her first shuttle mission, with veteran astronaut Matt Kowalsky (George Clooney) in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The shuttle is destroyed, leaving Stone and Kowalsky completely alone - tethered to nothing but each other and spiraling out into the blackness. The deafening silence tells them they have lost any link to Earth - and any chance for rescue. As fear turns to panic, every gulp of air eats away at what little oxygen is left. But the only way home may be to go further out into the terrifying expanse of space.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/6d45378ebea349b6008245fbd5ff0825-98.jpg", "nome": "Fantasia", "descricao": "\n                        A collection of animated interpretations of great works of Western classical music.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/ed0f84cdd6c344f929d5415492438b1a-98.jpg", "nome": "Spirited Away", "descricao": "\n                        A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free herself and return her family to the outside world. [Walt Disney Studios]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/b6e06ecf6920b8a703b11d5d6ed016f6-98.jpg", "nome": "Beauty and the Beast", "descricao": "\n                        This 'tale as old as time' follows the adventures of Belle, a bright young woman who finds herself imprisoned in a castle of a mysterious beast. With the assistance of the castle's enchanted staff, a delightful and tender romance develops between these two unlikely friends and Belle soon learns the most important lesson of all - that true beauty comes from within.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/62cf544058e622ab0c3eb4056cadf454-98.jpg", "nome": "Small Axe: Lovers Rock", "descricao": "\n                        A single evening at a house party in 1980s West London sets the scene, developing intertwined relationships against a background of violence, romance and music.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/0df3116e761c6f0e1b4568bfd25c6859-98.jpg", "nome": "Toy Story", "descricao": "\n                        Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. [Pixar]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/0e04af58341def29c7e6b00fb8fc0560-98.jpg", "nome": "The Bride of Frankenstein", "descricao": "\n                        Mary Shelley reveals the main characters of her novel survived: Dr. Frankenstein, goaded by an even madder scientist, builds his monster a mate.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/eb382c5075198bf6ad5d2e18329fae49-98.jpg", "nome": "Don't Look Now", "descricao": "\n                        A married couple grieving the recent death of their young daughter are in Venice when they encounter two elderly sisters, one of whom is psychic and brings a warning from beyond.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/aa5515688c769b5ffb92d2b07e671c2a-98.jpg", "nome": "The Social Network", "descricao": "\n                        On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg (Jesse Eisenberg) sits down at his computer and heatedly begins working on a new idea. In a fury of blogging and programming, what begins in his dorm room soon becomes a global social network and a revolution in communication. A mere six years and 500 million friends later, Mark Zuckerberg is the youngest billionaire in history... but for this entrepreneur, success leads to both personal and legal complications. [Columbia Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/419b98d7b4c547facb8eab4a95c18f19-98.jpg", "nome": "My Fair Lady", "descricao": "\n                        A snobbish phonetics professor agrees to a wager that he can take a flower girl and make her presentable in high society.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/b9ec74a47303ddde471895397fdac522-98.jpg", "nome": "Portrait of a Lady on Fire", "descricao": "\n                        France, 1760. Marianne is commissioned to paint the wedding portrait of H\u00e9lo\u00efse, a young woman who has just left the convent. Because she is a reluctant bride-to-be, Marianne arrives under the guise of companionship, observing H\u00e9lo\u00efse by day and secretly painting her by firelight at night. As the two women orbit one another, intimacy and attraction grow as they share H\u00e9lo\u00efse\u2019s first moments of freedom. H\u00e9lo\u00efse's portrait soon becomes a collaborative act of and testament to their love.  \n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/4f754e5f5da9c63346894604e8bf7ab1-98.jpg", "nome": "I Am Not Your Negro", "descricao": "\n                        Director Raoul Peck envisions the book James Baldwin never finished - a radical narration about race in America, using the writer\u2019s original words. He draws upon James Baldwin\u2019s notes on the lives and assassinations of Medgar Evers, Malcolm X, and Martin Luther King Jr to explore and bring a fresh and radical perspective to the current racial narrative in America. [Magnolia Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/601cd44b3177a0fa22ecbff0b5e46f57-98.jpg", "nome": "Woodstock", "descricao": "\n                        It happened on a small farm in upstate New York, for three remarkable days of mud and happiness in 1969, when over half a million people came together to celebrate life, love, and music--Woodstock. One camera crew was there, in the middle of everything, recording the live performances of many of the greatest singers and musicians of the era, and the joy, peace and rock 'n' roll experienced by hundreds of thousands. \n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/d8f76d702d47f9daf6757eb75bfbbbfd-98.jpg", "nome": "Double Indemnity", "descricao": "\n                        An insurance representative lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator's suspicions.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/1d88c6a5ee3f4abc2f4d9960d0a46074-98.jpg", "nome": "Rocks", "descricao": "\n                        A teenage girl suddenly finds herself struggling to take care of herself and her younger brother.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/643da4a256c833215eeb70d9e21d44a8-98.jpg", "nome": "Snow White and the Seven Dwarfs", "descricao": "\n                        Exiled into the dangerous forest by her wicked stepmother, a princess is rescued by seven dwarf miners who make her part of their household.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/c4d2cbc9f18e46e1f43623bc8d2ef510-98.jpg", "nome": "The Hurt Locker", "descricao": "\n                        When a new sergeant, James (Jeremy Renner), takes over a highly trained bomb disposal team amidst violent conflict, he surprises his two subordinates, Sanborn (Anthony Mackie) and Eldridge (Brian Geraghty), by recklessly plunging them into a deadly game of urban combat. James behaves as if he's indifferent to death. As the men struggle to control their wild new leader, the city explodes into chaos, and James' true character reveals itself in a way that will change each man forever. [Summit Entertainment]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/fef68d0d4857b7cb86c07744eb7d209f-98.jpg", "nome": "Anatomy of a Murder", "descricao": "\n                        In a murder trial, the defendant says he suffered temporary insanity after the victim raped his wife. What is the truth, and will he win his case?\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/a22d5b5f78fbbea4f6f8f19b6dbd00e5-98.jpg", "nome": "Zero Dark Thirty", "descricao": "\n                        For a decade, an elite team of intelligence and military operatives, working in secret across the globe, devoted themselves to a single goal: to find and eliminate Osama bin Laden. [Columbia Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/b7d4c9083c9f7f2f52cd076238430158-98.jpg", "nome": "Collective", "descricao": "\n                        Collective follows a heroic team of journalists as they uncover shocking, widespread corruption. After a deadly nightclub fire, the mysterious death of the owner of a powerful pharmaceutical firm, and the quiet resignation of a health minister\u2014seemingly unrelated events, all within weeks of each other\u2014the team of intrepid reporters exposes a much larger, much more explosive political scandal. COLLECTIVE is a fast-paced, real-time detective story about truth, accountability, and the value of an independent press in partisan times.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/65d12895ed2966db458a7a9724e6cc13-98.jpg", "nome": "A Separation", "descricao": "\n                        Set in contemporary Iran, A Separation is a compelling drama about the dissolution of a marriage. Simin wants to leave Iran with her husband Nader and daughter Termeh. Simin sues for divorce when Nader refuses to leave behind his Alzheimer-suffering father. Her request having failed, Simin returns to her parents' home, but Termeh decides to stay with Nader. When Nader hires a young woman to assist with his father in his wife's absence, he hopes that his life will return to a normal state. However, when he discovers that the new maid has been lying to him, he realizes that there is more on the line than just his marriage. [Sony Pictures Classic]\r\n\r\n\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/60843a0153e157509b414ffbf9f3b646-98.jpg", "nome": "WALL-E", "descricao": "\n                        After hundreds of lonely years of doing what he was built for, Wall-E discovers a new purpose in life when he meets a sleek search robot named EVE. [Walt Disney Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/a37a10a2b37af5fd71f23b4b160fe164-98.jpg", "nome": "Carol", "descricao": "\n                        Set in 1950s New York, two women from very different backgrounds find themselves in the throes of love. A young woman in her 20s, Therese Belivet (Rooney Mara), is a clerk working in a Manhattan department store and dreaming of a more fulfilling life when she meets Carol (Cate Blanchett), an alluring woman trapped in a loveless, convenient marriage. As an immediate connection sparks between them, the innocence of their first encounter dims and their connection deepens. While Carol breaks free from the confines of marriage, her husband (Kyle Chandler) threatens her competence as a mother when Carol\u2019s involvement with Therese and close relationship with her best friend Abby (Sarah Paulson) comes to light. As Carol leaves the comfort of home to travel with Therese, an internal journey of self-discovery coincides with her new sense of space. [TWC]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/5/21f99368ba464a0337630a5d5855f4fa-98.jpg", "nome": "Before Midnight", "descricao": "\n                        In this follow-up to Before Sunrise and Before Sunset, we meet Jesse and Celine nine years later in Greece. Almost two decades have passed since their first meeting on that train bound for Vienna.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/59e1400745c00b6f94c333dda75c16eb-98.jpg", "nome": "Amour", "descricao": "\n                        Georges and Anne are in their eighties. They are cultivated, retired music teachers. Their daughter, who is also a musician, lives abroad with her family. One day, Anne has an attack. The couple's bond of love is severely tested. [Sony Pictures Classics]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/9a774585c0cac7bc8047c14c2dcca8ae-98.jpg", "nome": "Dunkirk", "descricao": "\n                        Dunkirk opens as hundreds of thousands of British and Allied troops are surrounded by enemy forces. Trapped on the beach with their backs to the sea they face an impossible situation as the enemy closes in. [Warner Bros.]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/a72bcb6a00c638d0441580d298cb2caa-98.jpg", "nome": "The Man Who Shot Liberty Valance", "descricao": "\n                        A senator, who became famous for killing a notorious outlaw, returns for the funeral of an old friend and tells the truth about his deed.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/27666ec92b94fe5b57dc4f56abca6506-98.jpg", "nome": "The Searchers", "descricao": "\n                        An American Civil War veteran embarks on a journey to rescue his niece from the Comanches.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/eae2693f79c8191364f38d01421618fc-98.jpg", "nome": "45 Years", "descricao": "\n                        There is just one week until Kate Mercer's (Charlotte Rampling) 45th wedding anniversary and the planning for the party is going well. But then a letter arrives for her husband (Tom Courtenay). The body of his first love has been discovered, frozen and preserved in the icy glaciers of the Swiss Alps. By the time the party is upon them, five days later, there may not be a marriage left to celebrate. [IFC Films]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/1/06526a61907c3757688d1107a490fe64-98.jpg", "nome": "Taxi Driver", "descricao": "\n                        Scorsese\u2019s 1976 masterpiece is the all-too-real story of a psychotic New York cabby who is driven to violence in an attempt to rescue a teenage prostitute.  [Sony]\r\n\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/08594c7ecaad52240a86dc1b4e720781-98.jpg", "nome": "The Servant", "descricao": "\n                        The Servant looks at the decaying British class system through the relationship between an aristocrat and his scheming butler.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/0267c3bb3c2a782833e67bab398383e5-98.jpg", "nome": "Pulp Fiction", "descricao": "\n                        Several inter-locking stories of crime and intrigue form a temporal mosaic set in the Los Angeles underworld.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/2/a0beacc37c952d6ec007d6bb9d24ba89-98.jpg", "nome": "The Manchurian Candidate", "descricao": "\n                        John Frankenheimer's gripping political thriller about a group of American soldiers who are captured and brainwashed into becoming sleeper agents. (MGM)\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/4d19fca1d081c8143c2bf64657fe0a2f-98.jpg", "nome": "Mr. Turner", "descricao": "\n                        Mr. Turner explores the last quarter century of the life of the great if eccentric British painter J.M.W. Turner (Timothy Spall). Profoundly affected by the death of his father, loved by a housekeeper he takes for granted and occasionally exploits sexually, he forms a close relationship with a seaside landlady with whom he eventually lives incognito in Chelsea, where he dies. Throughout this, he travels, paints, stays with the country aristocracy, visits brothels, is a popular if anarchic member of the Royal Academy of Arts, has himself strapped to the mast of a ship so that he can paint a snowstorm, and is both celebrated and reviled by the public and by royalty.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/9/c4f0ff0f354fdbfa6411a77d60d0203e-98.jpg", "nome": "The Irishman", "descricao": "\n                        The Irishman is an epic saga of organized crime in post-war America told through the eyes of World War II veteran Frank Sheeran (Robert De Niro), a hustler and hitman who worked alongside some of the most notorious figures of the 20th Century. Spanning decades, the film chronicles one of the greatest unsolved mysteries in American history, the disappearance of legendary union boss Jimmy Hoffa, and offers a monumental journey through the hidden corridors of organized crime: its inner workings, rivalries and connections to mainstream politics.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/f4d98c7c9591b5835ab338d96a184ab3-98.jpg", "nome": "Amazing Grace", "descricao": "\n                        A documentary presenting Aretha Franklin with choir at the New Bethel Baptist Church in Watts, Los Angeles in January 1972.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/00e60609ffe65d0521f921e399686cf6-98.jpg", "nome": "Grave of the Fireflies (1988)", "descricao": "\n                        A young boy and his little sister struggle to survive in Japan during World War II.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/2e62ca50884e902b1d7e1e7a66d1db2e-98.jpg", "nome": "The Wild Child", "descricao": "\n                        In a French forest in 1798, a child is found who cannot walk, speak, read or write. A doctor becomes interested in the child and patiently attempts to civilize him.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/19f77292d0d17a650d04be99d5874849-98.jpg", "nome": "Shadow of a Doubt", "descricao": "\n                        A young woman discovers her visiting uncle may not be the man he seems to be.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/6/4ef454cab506fab08119c0efc252a981-98.jpg", "nome": "Inside Out", "descricao": "\n                        Growing up can be a bumpy road, and it\u2019s no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Like all of us, Riley is guided by her emotions: Joy (Amy Poehler), Fear (Bill Hader), Anger (Lewis Black), Disgust (Mindy Kaling) and Sadness (Phyllis Smith). The emotions live in Headquarters, the control center inside Riley\u2019s mind, where they help advise her through everyday life. As Riley and her emotions struggle to adjust to a new life in San Francisco, turmoil ensues in Headquarters. Although Joy, Riley\u2019s main and most important emotion, tries to keep things positive, the emotions conflict on how best to navigate a new city, house, and school. [Pixar]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/ad93b373d50d432ecb7575e553e998bf-98.jpg", "nome": "Sideways", "descricao": "\n                        Two old friends set off on a wine-tasting road trip...only to veer dizzily sideways into a wry, comedic exploration of the crazy vicissitudes of love and friendship, the damnable persistence of loneliness and dreams and the enduring war between Pinot and Cabernet.  [Fox Searchlight Pictures]\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/8f9e48d7c87b91706a0b68774721fd7c-98.jpg", "nome": "Schindler's List", "descricao": "\n                        Steven Spielberg's epic drama tells the compelling true story of German businessman Oskar Schindler (Neeson) who comes to Nazi-occupied Poland looking for economic prosperity and leaves as a savior. (History in Film)\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/7/a4b83434b34ee5c82b196ec77792db66-98.jpg", "nome": "Meet Me in St. Louis", "descricao": "\n                        Young love and childish fears highlight a year in the life of a turn-of-the-century family.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/3/14eeef9b4c24fd2b8c3cefb1d37262f3-98.jpg", "nome": "The Apartment", "descricao": "\n                        A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/4/5d4637c187b702dbc61f8dd540125e44-98.jpg", "nome": "Apocalypse Now", "descricao": "\n                        During the Vietnam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade colonel who has set himself up as a god among a local tribe.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/8/5a6387be22097d5a87c2edaa63370e41-98.jpg", "nome": "Petite Maman", "descricao": "\n                        Nelly has just lost her grandmother and is helping her parents clean out her mother's childhood home. She explores the house and the surrounding woods. One day she meets a girl her same age building a treehouse.\n                        "}
{"imagem": null, "nome": null, "descricao": null}
{"imagem": "https://static.metacritic.com/images/products/movies/0/421a11e77dde7fff0233805963ccf703-98.jpg", "nome": "The Gunfighter", "descricao": "\n                        Notorious gunfighter Jimmy Ringo rides into town to find his true love, who doesn't want to see him. He hasn't come looking for trouble, but trouble finds him around every corner.\n                        "}
